### ISSUE TITLE
Save settings next time GUI is opened

### ISSUE THREAD

**Issue by DavidMSou** [KeyofBlueS/xfce4-display-profile-chooser#6]
Version: 0.4.2

Hi! Is it possible to add a tick option to save the configurations set on the GUI window?
I open the GUI via a shortcut to the .sh script directly and always have to set it; for example, the Skip checks on inactive outputs.

Thank you!

**Comment by KeyofBlueS** [comment]
Hi @DavidMSou, you can add the option in the command:

`$ xfce4-display-profile-chooser --skip-inactive --gui`

Is this a working solution for you?

**Comment by DavidMSou** [comment]
Yes indeed! Thank you!
It would make an excellent feature request, though.

Regards!

**Comment by KeyofBlueS** [comment]
Actually I had previously ruled out using a config file, but feel free to reopen the issue if you think it must be a vital feature.

Thanks and best regards.
